# Generated by Django 6.0.3 on 2026-03-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('color', models.CharField(default='#6366f1', help_text='Couleur hexadécimale (ex: #6366f1)', max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône (ex: 'work', 'home', 'shopping')", max_length=50, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Terminée'), ('cancelled', 'Annulée')], default='todo', max_length=15, verbose_name='Statut')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Échéance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='app.category', verbose_name='Catégorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='app.tag', verbose_name='Étiquettes')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='app_task_status_ab5cd1_idx'), models.Index(fields=['priority'], name='app_task_priorit_014183_idx'), models.Index(fields=['due_date'], name='app_task_due_dat_2ed033_idx'), models.Index(fields=['category'], name='app_task_categor_0f2e73_idx')],
            },
        ),
    ]
